#!/bin/bash
. "$HOME/i3.env"

curl -si -H "Authorization: token $GITHUB_TOKEN" https://api.github.com/notifications |  
	awk -v bl=1 'bl{bl=0; h=($0 ~ /HTTP\/1/)} /^\r?$/{bl=1} {print $0>(h?"header":"body")}'

header=$(<header)
body=$(<body)

echo "$body" | jq '. | length'

sleep $( echo $header | grep -oP '(?<=X-Poll-Interval: )\d*' )
