#!/bin/bash

touch /tmp/ip

IP="$(</tmp/ip)"

if [ -z "$IP" ]; then
  IP=$(dig +short myip.opendns.com @resolver1.opendns.com)
  echo "$IP" > /tmp/ip
fi

case $BLOCK_BUTTON in
    1) echo -n "$IP" | xclip -q -se c  ;;
esac

echo "$IP"
